title: Mohamed Ajanif # your name (or website title) here
logo: "profile.jpg" # your photo (or logo) here
description: >
  <br>
  <strong>Welcome to my portfolio!</strong>
  <br><br>
  I'm an MSc Economics and Politics graduate from the University of Freiburg and currently a Research Associate at HHL Leipzig Graduate School of Management. My interests include competition, regulation, industrial economics and public policy, with a strong empirical focus. 
  <br><br>
  Feel free to get in touch or collaborate.
  <br><br>
  <a href="https://www.linkedin.com/in/ajanif/">View my LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
show_downloads: false     # ← This ensures download buttons are off
github: [is_project_page: false] # ← Add this to hide the automatic GitHub profile link
google_analytics: UA-000000-0 # your Google Analytics tracking ID here

colors:
  crimson: '#900C3F'
